In [1]:
import numpy as np



In [2]:
data = np.load('data.npy')
data

array([[[   0.        ,   15.979     ],
        [   0.        , 1309.76484713],
        [   0.        , 1844.71318879],
        [   0.        , 2491.77837707],
        [   0.        , 3424.73525466]],

       [[   0.        ,   14.179     ],
        [   0.        ,  999.3360631 ],
        [   0.        , 1541.45863057],
        [   0.        , 2116.69927793],
        [   0.        , 3444.28942247]],

       [[   0.        ,   14.579     ],
        [   0.        , 1175.57540553],
        [   0.        , 2680.63438756],
        [   0.        , 3838.23214015],
        [   0.        , 4336.12771349]],

       ...,

       [[  15.8546    ,    0.        ],
        [1116.55239726,    0.        ],
        [2408.99125539,    0.        ],
        [3300.70669622,    0.        ],
        [4541.41532008,    0.        ]],

       [[  14.4152    ,   21.6228    ],
        [1106.09527109, 1659.14290664],
        [2511.69827081, 3767.54740621],
        [2961.77423194, 4442.6613479 ],
        [3822.08191

In [3]:
financeStudent = 0
CSStudent = 0
fintechStudent = 0

for d in data:
    if d[0][0]==0:
        CSStudent+=1
    elif d[0][1]==0:
        financeStudent+=1
    else:
        fintechStudent+=1

In [4]:
financeStudent

356

In [5]:
CSStudent

374

In [6]:
fintechStudent

270

In [8]:
finalFinance = []
finalCS = []
finalFintech = []

In [9]:
tmpData = []
for d in data:
    tmpData.append(d[-1])
tmpData

[array([   0.        , 3424.73525466]),
 array([   0.        , 3444.28942247]),
 array([   0.        , 4336.12771349]),
 array([   0.        , 5047.04110482]),
 array([   0.        , 4271.72991357]),
 array([5099.93529698, 7649.90294547]),
 array([4383.8240963,    0.       ]),
 array([   0.       , 4080.0932196]),
 array([   0.        , 4965.39204769]),
 array([4707.53100836, 7061.29651254]),
 array([4665.28109203,    0.        ]),
 array([   0.        , 4551.72111975]),
 array([   0.        , 3776.20878609]),
 array([3086.60131249, 4629.90196873]),
 array([3590.22634627,    0.        ]),
 array([4405.36292615, 6608.04438922]),
 array([   0.        , 4445.18014625]),
 array([   0.        , 4508.14379531]),
 array([   0.       , 4189.1068513]),
 array([4231.9914053 , 6347.98710796]),
 array([   0.        , 4990.34279513]),
 array([   0.        , 3980.31751396]),
 array([   0.        , 3854.53258555]),
 array([4202.77020415,    0.        ]),
 array([4032.52535637,    0.        ]),
 array

In [10]:
for t in tmpData:
    if t[0]==0:
        finalCS.append(t)
    elif t[1]==0:
        finalFinance.append(t)
    else:
        finalFintech.append(t)

In [13]:
finalCS = np.array(finalCS)
finalCS

array([[   0.        , 3424.73525466],
       [   0.        , 3444.28942247],
       [   0.        , 4336.12771349],
       [   0.        , 5047.04110482],
       [   0.        , 4271.72991357],
       [   0.        , 4080.0932196 ],
       [   0.        , 4965.39204769],
       [   0.        , 4551.72111975],
       [   0.        , 3776.20878609],
       [   0.        , 4445.18014625],
       [   0.        , 4508.14379531],
       [   0.        , 4189.1068513 ],
       [   0.        , 4990.34279513],
       [   0.        , 3980.31751396],
       [   0.        , 3854.53258555],
       [   0.        , 3470.31555057],
       [   0.        , 5159.33948565],
       [   0.        , 4575.63513899],
       [   0.        , 4359.07913322],
       [   0.        , 3537.22696448],
       [   0.        , 4188.87417301],
       [   0.        , 5246.16613541],
       [   0.        , 4900.64407278],
       [   0.        , 3610.46110864],
       [   0.        , 4773.15882083],
       [   0.        , 37

In [14]:
finalFinance = np.array(finalFinance)
finalFinance

array([[4383.8240963 ,    0.        ],
       [4665.28109203,    0.        ],
       [3590.22634627,    0.        ],
       [4202.77020415,    0.        ],
       [4032.52535637,    0.        ],
       [4346.69083182,    0.        ],
       [3244.02174223,    0.        ],
       [3239.61912994,    0.        ],
       [4078.19967604,    0.        ],
       [5382.83785823,    0.        ],
       [5156.31533701,    0.        ],
       [5114.89961089,    0.        ],
       [3584.05721992,    0.        ],
       [4231.10758765,    0.        ],
       [4470.2588047 ,    0.        ],
       [3323.14197535,    0.        ],
       [3910.7748297 ,    0.        ],
       [3652.5305526 ,    0.        ],
       [3653.71742157,    0.        ],
       [3415.0241218 ,    0.        ],
       [4080.3088264 ,    0.        ],
       [4598.72763652,    0.        ],
       [3976.80174886,    0.        ],
       [3706.76854712,    0.        ],
       [3353.28703039,    0.        ],
       [3559.44553382,   

In [15]:
finalFintech = np.array(finalFintech)
finalFintech

array([[5099.93529698, 7649.90294547],
       [4707.53100836, 7061.29651254],
       [3086.60131249, 4629.90196873],
       [4405.36292615, 6608.04438922],
       [4231.9914053 , 6347.98710796],
       [4086.38037324, 6129.57055986],
       [3410.03342031, 5115.05013046],
       [4152.54773517, 6228.82160275],
       [4044.73018186, 6067.09527278],
       [4233.96958741, 6350.95438111],
       [4171.26408484, 6256.89612726],
       [4169.50959953, 6254.2643993 ],
       [3210.31795488, 4815.47693231],
       [5426.24909985, 8139.37364977],
       [4280.90418297, 6421.35627445],
       [3319.35060795, 4979.02591193],
       [4633.18295278, 6949.77442917],
       [3321.29428962, 4981.94143442],
       [4659.19387661, 6988.79081491],
       [3833.32742888, 5749.99114332],
       [3948.67555792, 5923.01333689],
       [4872.17557641, 7308.26336461],
       [3980.76011328, 5971.14016992],
       [4186.63663278, 6279.95494918],
       [4697.55053475, 7046.32580213],
       [4066.5299028 , 60

In [17]:
np.save('FinTechFinal', finalFintech, allow_pickle=True, fix_imports=True)
np.save('FinanceFinal', finalFinance, allow_pickle=True, fix_imports=True)
np.save('CSFinal', finalCS, allow_pickle=True, fix_imports=True)